version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports: 
      - '5432:5432'
    volumes:
      - video-db:/var/lib/postgresql/data

  video:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    ports:
      - '8080:8080'

volumes:
  video-db: